version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: data_base
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-networks

  server:
    build:
      context: ./server
      args:
        DATABASE_URL: postgres://user:password@db:5432/data_base
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/data_base
    volumes:
      - ./server:/app
      - /app/mode_modules
    networks:
      - app-networks

  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      SERVER_URL: http://host.docker.internal:3001/api
    networks:
      - app-networks

volumes:
  postgres-data:


networks:
  app-networks:
    driver: bridge
